# Travis-CI build script for sdsl-lite

language: cpp

sudo: false

matrix:
  include:
    - env: MYCC="gcc-4.9" MYCXX="g++-4.9" 
      os: linux
      addons: &gcc49
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9

    - env: MYCC="gcc-5" MYCXX="g++-5" 
      os: linux
      addons: &gcc5
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5

    - env: MYCC="clang-3.7" MYCXX="clang++-3.7"
      os: linux
      addons: &clang37
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - clang-3.7

    # clang 3.7 on MacOSX without AddressSanitizer, Debug & Release
    - env: MYCC="clang" MYCXX="clang++" 
      os: osx

    - env: MYCC="clang" MYCXX="clang++"
      os: osx

before_script:
  - export CXX=$MYCXX
  - export CC=$MYCC
  - $CXX --version
  - cmake --version

script:
  - ./install.sh ..
